name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Backend format check
        run: dotnet format --verify-no-changes EventTicketing.sln

  unit-tests:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Backend unit tests
        run: dotnet test --project EventTicketing.Tests -- --filter-not-trait "Category=Integration"
